spring:
  config:
    activate:
      on-profile: dev, test, prod
    import: "optional:configserver:http://localhost:8888"
  application:
    name: catalog
custom:
  page:
    default-size: 10
  strategy:
    popularity:
      item-is-considered-popular-at-orders-count:
        25
    shoes-size:
      min: 30
      max: 46
  category:
    img-path-prefix:
      men: catalog/src/main/resources/images/category/men/
      women: catalog/src/main/resources/images/category/women/
springdoc:
  api-docs:
    path: /docs # these urls will be used to load the api docs of this service by the api gateway
  swagger-ui:
    enabled: false
server:
  servlet:
    context-path: /catalog
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/items_data
    username:
    password:
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8000
---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      settings:
        trace: true
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER;
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    defer-datasource-initialization: true
server:
  port: 8001
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://catalog-db:5432/items_data
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
server:
  port: 8000