spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/items_data
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  config:
    import: 'optional:configserver:http://localhost:8888'
  application:
    name: catalog
server:
  port: 8000
custom:
  page:
    size:
      main: 20
      landing-page: 12
  strategy:
    popularity:
      item-is-considered-popular-at-orders-count:
        25
  category:
    img-path-prefix:
      men: catalog/src/main/resources/images/category/men/
      women: catalog/src/main/resources/images/category/women/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    path: /items/docs # these urls will be used to load the api docs of this service by the api gateway
  swagger-ui:
    enabled: false