spring:
  config:
    activate:
      on-profile: dev, test
    import: "optional:configserver:http://localhost:8888"
  application:
    name: catalog
custom:
  page:
    size:
      main: 20
      landing-page: 12
  strategy:
    popularity:
      item-is-considered-popular-at-orders-count:
        25
    shoes-size:
      min: 30
      max: 46
  category:
    img-path-prefix:
      men: catalog/src/main/resources/images/category/men/
      women: catalog/src/main/resources/images/category/women/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    path: /items/docs # these urls will be used to load the api docs of this service by the api gateway
  swagger-ui:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/items_data
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8000
---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      settings:
        trace: true
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER;
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    defer-datasource-initialization: true
server:
  port: 8001