spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customers_data
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customers
server:
  port: 8100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
