spring:
  config:
    activate:
      on-profile: dev, prod
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.59:8400/keycloak/realms/e-commerce
          jwk-set-uri: http://192.168.0.59:8400/keycloak/realms/e-commerce/protocol/openid-connect/certs
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs
    urls:
      - url: /catalog/docs
        name: Catalog Service
server:
  port: 8765
---
spring:
  config:
    activate:
      on-profile: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/