server:
  port: 8765
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8400/keycloak/embedded/realms/e-commerce
          jwk-set-uri: http://localhost:8400/keycloak/embedded/realms/e-commerce/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs
    urls:
      - url: /catalog/docs
        name: Catalog Service