spring:
  application:
    name: api-gateway
---
spring:
  config:
    activate:
      on-profile: dev
    import: configserver:http://localhost:8888
---
spring:
  config:
    activate:
      on-profile: prod
    import: configserver:http://config:8888