server:
  port: 8765
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs
    urls:
      - url: /catalog/docs
        name: Catalog Service