#spring.datasource.url=jdbc:postgresql://172.17.0.6:5433/items_data
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/items_data
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  config:
    import: 'optional:configserver:http://localhost:8888'
#    import: 'optional:configserver:http://cloud-config:8888'
  application:
    name: items-data
server:
  port: 8000
custom:
  page:
    size: 20
  strategy:
    popular-items-limit-in-scope: 10
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://naming-server:8761/eureka

#logging.level.org.springframework.web.client.RestTemplate=DEBUG
#logging.level.root=OFF
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace