spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_data
    username: postgres
    password: xurM5M4HBt
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: spacefincher@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: users
  security:
    oauth2:
      resourceserver:
        registration:
          google:
            client-id: 366892792903-hcvb0cr5rdfe6afvl628isd4l900uai6.apps.googleusercontent.com
            client-secret:
            redirect-uri: http://localhost:8765/users/registration/customer/google
            scope: >
              https://www.googleapis.com/auth/userinfo.profile
              https://www.googleapis.com/auth/userinfo.email
              openid
server:
  port: 8100
  servlet:
    context-path: /users
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
frontend-base-url: http://localhost:4200
