spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_data
    username: postgres
    password: xurM5M4HBt
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: users
server:
  port: 8100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
