spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  security:
    oauth2:
      issuers:
        - uri: http://keycloak:8400/keycloak/realms/e-commerce
          username-json-path: $.preferred_username
          roles-json-path: $.realm_access.roles
        - uri: https://accounts.google.com
          username-json-path: $.email
          default-roles: CUSTOMER
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
    urls:
      - url: /catalog/docs
        name: Catalog
      - url: /oauth2/docs
        name: Authorization Server
      - url: /customers/docs
        name: Customers
      - url: /orders/docs
        name: Orders
      - url: /reviews/docs
        name: Reviews
server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/