spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_data
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: orders
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    topic: order-events
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap-servers: localhost:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8200
  servlet:
    context-path: /orders
custom:
  page:
    default-size: 10