spring:
  application:
    name: reviews
  data:
    mongodb:
      uri: mongodb://reviews-db:27017/reviews_data
      database: reviews_data
      uuid-representation: java_legacy
  kafka:
    topic: rating-events
    bootstrap-servers: kafka:29092
    producer:
      bootstrap-servers: kafka:29092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
custom:
  page:
    default-size: 10
server:
  port: 8300
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka