spring:
  application:
    name: reviews
  data:
    mongodb:
      uri: mongodb://localhost:27017/reviews_data
      database: reviews_data
      uuid-representation: java_legacy
      init-file: /init.json
custom:
  page:
    default-size: 10
server:
  port: 8300
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka