spring:
  application:
    name: reviews
  data:
    mongodb:
      uri: mongodb://localhost:27017/reviews_data
      database: reviews_data
      uuid-representation: java_legacy
  kafka:
    topic: rating-events
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
custom:
  page:
    default-size: 10
server:
  port: 8300
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    path: /reviews/docs
  swagger-ui:
    enabled: true