server:
  port: 8400
spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER;
keycloak:
  server:
    contextPath: /auth
    adminUser:
      username:
      password:
    realmImportFile: e-commerce-realm.json