server:
  port: 8400
spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER;
  secondary-datasource:
    username:
    password:
    url: jdbc:postgresql://localhost:5432/keycloak
  application:
    name: keycloak
keycloak:
  server:
    adminUser:
      username:
      password:
    adminClient:
      clientId: admin-cli
      clientSecret: "**********"
    realmImportFile: e-commerce-realm.json
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka