spring:
  application:
    name: config-server
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config/catalog
            - classpath:/config/authorization
            - classpath:/config/customers
---
spring:
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bekrenov-r/ecommerce-app-config